### PR TITLE
Enhance/new structure

### LINKED ISSUE #61: Restructure the project tree with better sub-packages and module management
Currently, all the python modules are in the main directory. We have to manage all those modules inside the sub-packages and update the `setup.py` to be able to find those sub-packages.

### PR DESCRIPTION
**Pull request by Anyesh**
- Restructure the `usagelogger` package

**Note:** To test this PR one should install this from pip. Packages and sub-packages work fine if we just clone the project and run it but while installing from `pip` `setup.py` has to be configured in such a way that it can find all the sub-packages which need to be built. So I suggest while testing this PR use:
```git
pip install git+https://github.com/resurfaceio/logger-python.git@enhance/new-structure
```

### CODE REVIEW

**Comment by Anyesh** [comment]
The old middleware modules are preserved for backward compatibility and a warning is raised to suggest users import modules from the middleware package.

**Comment by monrax** [comment]
Looks great! All test apps work as expected. However, there is an issue with the unit tests: the modules can't be imported as `tests` is not a package with the new structure. I attach `pytest`'s output below:
```
================================================= test session starts =================================================
platform win32 -- Python 3.9.5, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: ~, configfile: pyproject.toml
collected 28 items / 6 errors / 22 selected

======================================================= ERRORS ========================================================
_____________________________________ ERROR collecting tests/test_base_logger.py ______________________________________
ImportError while importing test module '~\tests\test_base_logger.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\appdata\local\programs\python\python39\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests\test_base_logger.py:5: in <module>
    from tests.test_helper import DEMO_URL, MOCK_AGENT, MOCK_URLS_DENIED, MOCK_URLS_INVALID
E   ModuleNotFoundError: No module named 'tests.test_helper'
_____________________________________ ERROR collecting tests/test_http_logger.py ______________________________________
ImportError while importing test module '~\tests\test_http_logger.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\appdata\local\programs\python\python39\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests\test_http_logger.py:4: in <module>
    from tests.test_helper import DEMO_URL
E   ModuleNotFoundError: No module named 'tests.test_helper'
__________________________________ ERROR collecting tests/test_http_logger_rules.py ___________________________________
ImportError while importing test module '~\tests\test_http_logger_rules.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\appdata\local\programs\python\python39\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests\test_http_logger_rules.py:4: in <module>
    from tests.test_helper import (
E   ModuleNotFoundError: No module named 'tests.test_helper'
_____________________________________ ERROR collecting tests/test_http_message.py _____________________________________
ImportError while importing test module '~\tests\test_http_message.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\appdata\local\programs\python\python39\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests\test_http_message.py:4: in <module>
    from tests.test_helper import (
E   ModuleNotFoundError: No module named 'tests.test_helper'
__________________________________ ERROR collecting tests/test_http_request_impl.py ___________________________________
ImportError while importing test module '~\tests\test_http_request_impl.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\appdata\local\programs\python\python39\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests\test_http_request_impl.py:4: in <module>
    from tests.test_helper import MOCK_JSON, MOCK_URL
E   ModuleNotFoundError: No module named 'tests.test_helper'
__________________________________ ERROR collecting tests/test_http_response_impl.py __________________________________
ImportError while importing test module 'ROOTDIR\tests\test_http_response_impl.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\appdata\local\programs\python\python39\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests\test_http_response_impl.py:4: in <module>
    from tests.test_helper import MOCK_JSON, MOCK_URL
E   ModuleNotFoundError: No module named 'tests.test_helper'
=============================================== short test summary info ===============================================
ERROR tests/test_base_logger.py
ERROR tests/test_http_logger.py
ERROR tests/test_http_logger_rules.py
ERROR tests/test_http_message.py
ERROR tests/test_http_request_impl.py
ERROR tests/test_http_response_impl.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 6 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================== 6 errors in 1.08s ==================================================
```

**Comment by Anyesh** [comment]
Thanks for reviewing it 🤗

Usagelogger is used as a package in other applications so in that package we should not include our unit tests. We can but we should not so the whole tests are ignored. If you want to unit test the package you should download/clone it and install the dev requirements in which we have `-e .` command which will install the current package itself directly from the file (`pip install -e .`). In that development mode you can unit test the app.

**Comment by Anyesh** [comment]
Also, the last commit 4fffe70 will remove the need of  `pip install -e .` just for convenience.

**Comment by monrax** [comment]
All tests (test apps + unit tests) passed! 🎉

**Review by monrax — APPROVED** [review]
Great work!

**Comment by Anyesh** [comment]
I have added cross-platform and cross-environment tests for the logger. 🙌

**Comment by Anyesh** [comment]
It would be nice if we could merge this PR before our upcoming major resurface update.

**Pull request closed without merging**
